wip

diff --git a/.github/workflows/debug-metadata.yml b/.github/workflows/debug-metadata.yml
--- a/.github/workflows/debug-metadata.yml
+++ b/.github/workflows/debug-metadata.yml
@@ -1,60 +1,60 @@
-name: Debug Metadata
+# name: Debug Metadata
 
-on:
-  push:
+# on:
+#   push:
 
-concurrency:
-  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
-  cancel-in-progress: true
+# concurrency:
+#   group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
+#   cancel-in-progress: true
 
-jobs:
-  integration-tests:
-    name: Run TGI Integration Tests
-    runs-on:
-      group: gcp-ct5lp-hightpu-8t
+# jobs:
+#   integration-tests:
+#     name: Run TGI Integration Tests
+#     runs-on:
+#       group: gcp-ct5lp-hightpu-8t
     
-    steps:
-      - name: Install DNS utilities
-        run: |
-          sudo apt-get update -y
-          sudo apt-get install -y dnsutils iputils-ping curl
+#     steps:
+#       - name: Install DNS utilities
+#         run: |
+#           sudo apt-get update -y
+#           sudo apt-get install -y dnsutils iputils-ping curl
 
     
 
-      - name: Debug metadata
-        run: |
-          echo "nslookup metadata.google.internal"
-          nslookup metadata.google.internal
+#       - name: Debug metadata
+#         run: |
+#           echo "nslookup metadata.google.internal"
+#           nslookup metadata.google.internal
 
-          echo "ping -c 3 metadata.google.internal"
-          ping -c 3 metadata.google.internal
+#           echo "ping -c 3 metadata.google.internal"
+#           ping -c 3 metadata.google.internal
 
-          echo "ping -c 3 169.254.169.254"
-          ping -c 3 169.254.169.254
+#           echo "ping -c 3 169.254.169.254"
+#           ping -c 3 169.254.169.254
 
-          echo "Get the IP address of metadata.google.internal using getent"
-          # Get the IP address of metadata.google.internal using getent
-          METADATA_IP=$(getent hosts metadata.google.internal | awk '{ print $1 }')
-          echo "Metadata server IP address: ${METADATA_IP}"
+#           echo "Get the IP address of metadata.google.internal using getent"
+#           # Get the IP address of metadata.google.internal using getent
+#           METADATA_IP=$(getent hosts metadata.google.internal | awk '{ print $1 }')
+#           echo "Metadata server IP address: ${METADATA_IP}"
           
-          echo "Fetching instance metadata directory:"
-          curl -s http://metadata.google.internal/computeMetadata/v1/instance/ -H "Metadata-Flavor: Google"
-          echo
+#           echo "Fetching instance metadata directory:"
+#           curl -s http://metadata.google.internal/computeMetadata/v1/instance/ -H "Metadata-Flavor: Google"
+#           echo
 
-          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" "http://metadata.google.internal/computeMetadata/v1/instance/image" -H "Metadata-Flavor: Google")
-          RESPONSE=$(curl -s "http://metadata.google.internal/computeMetadata/v1/instance/image" -H "Metadata-Flavor: Google")
-          echo "Status code: $STATUS_CODE"
-          echo "Metadata response: $RESPONSE"
-          if [ "$STATUS_CODE" -ne 200 ]; then
-            echo "Failed to fetch instance image metadata"
-            exit 1
-          fi
+#           STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" "http://metadata.google.internal/computeMetadata/v1/instance/image" -H "Metadata-Flavor: Google")
+#           RESPONSE=$(curl -s "http://metadata.google.internal/computeMetadata/v1/instance/image" -H "Metadata-Flavor: Google")
+#           echo "Status code: $STATUS_CODE"
+#           echo "Metadata response: $RESPONSE"
+#           if [ "$STATUS_CODE" -ne 200 ]; then
+#             echo "Failed to fetch instance image metadata"
+#             exit 1
+#           fi
 
-          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" "http://metadata.google.internal/computeMetadata/v1/instance/attributes/tpu-env" -H "Metadata-Flavor: Google")
-          RESPONSE=$(curl -s "http://metadata.google.internal/computeMetadata/v1/instance/attributes/tpu-env" -H "Metadata-Flavor: Google")
-          echo "Status code: $STATUS_CODE"
-          echo "Metadata response: $RESPONSE"
-          if [ "$STATUS_CODE" -ne 200 ]; then
-            echo "Failed to fetch TPU environment metadata"
-            exit 1
-          fi
+#           STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" "http://metadata.google.internal/computeMetadata/v1/instance/attributes/tpu-env" -H "Metadata-Flavor: Google")
+#           RESPONSE=$(curl -s "http://metadata.google.internal/computeMetadata/v1/instance/attributes/tpu-env" -H "Metadata-Flavor: Google")
+#           echo "Status code: $STATUS_CODE"
+#           echo "Metadata response: $RESPONSE"
+#           if [ "$STATUS_CODE" -ne 200 ]; then
+#             echo "Failed to fetch TPU environment metadata"
+#             exit 1
+#           fi
