trying to configure dns to solve the google.internal

diff --git a/.github/workflows/test-pytorch-xla-tpu-tgi-integration.yml b/.github/workflows/test-pytorch-xla-tpu-tgi-integration.yml
--- a/.github/workflows/test-pytorch-xla-tpu-tgi-integration.yml
+++ b/.github/workflows/test-pytorch-xla-tpu-tgi-integration.yml
@@ -77,15 +77,15 @@ jobs:
           apt-get install -y docker.io dnsutils
 
 
-      - name: Check DNS
-        run: |
-          METADATA_IP=$(getent hosts metadata.google.internal | awk '{ print $1 }')
-          echo "Found metadata server IP: ${METADATA_IP}"
+      # - name: Check DNS
+      #   run: |
+      #     METADATA_IP=$(getent hosts metadata.google.internal | awk '{ print $1 }')
+      #     echo "Found metadata server IP: ${METADATA_IP}"
           
-          if [ -z "${METADATA_IP}" ]; then
-            echo "Error: Could not resolve metadata.google.internal"
-            exit 1
-          fi
+      #     if [ -z "${METADATA_IP}" ]; then
+      #       echo "Error: Could not resolve metadata.google.internal"
+      #       exit 1
+      #     fi
             
 
       - name: Debug XLA (build container)
@@ -95,21 +95,23 @@ jobs:
       - name: Debug XLA (run container)
         run: |
 
-          METADATA_IP=$(getent hosts metadata.google.internal | awk '{ print $1 }')
-          echo "Found metadata server IP: ${METADATA_IP}"
+          # METADATA_IP=$(getent hosts metadata.google.internal | awk '{ print $1 }')
+          # echo "Found metadata server IP: ${METADATA_IP}"
           
-          if [ -z "${METADATA_IP}" ]; then
-            echo "Error: Could not resolve metadata.google.internal"
-            exit 1
-          fi
+          # if [ -z "${METADATA_IP}" ]; then
+          #   echo "Error: Could not resolve metadata.google.internal"
+          #   exit 1
+          # fi
 
           docker run --rm \
             --shm-size=16G \
             --privileged \
             --network host \
             --ipc host \
-            # --add-host "metadata.google.internal:${METADATA_IP}" \
             debug-dind
+
+          # --add-host "metadata.google.internal:${METADATA_IP}" \
+
 
 
 #     docker run -d --name tgi-tests-${MODEL_ID##*/} \
