trying to configure dns to solve the google.internal

diff --git a/.github/workflows/test-pytorch-xla-tpu-tgi-integration.yml b/.github/workflows/test-pytorch-xla-tpu-tgi-integration.yml
--- a/.github/workflows/test-pytorch-xla-tpu-tgi-integration.yml
+++ b/.github/workflows/test-pytorch-xla-tpu-tgi-integration.yml
@@ -74,33 +74,35 @@ jobs:
       - name: Debug XLA (install dependencies)
         run: |
           apt-get update -y
-          apt-get install -y docker.io dnsutils
+          apt-get install -y docker.io
 
-      - name: Debug XLA (build container)
-        run: |
-          docker build -t debug-dind debug-dind/
+      # - name: Debug XLA (build container)
+      #   run: |
+      #     docker build -t debug-dind debug-dind/
 
             
-
-
-      - name: Debug XLA (run container)
+      - name: Debug DNS
         run: |
+          docker run busybox nslookup metadata.google.internal
 
-          METADATA_IP=$(getent hosts metadata.google.internal | awk '{ print $1 }')
-          echo "Found metadata server IP: ${METADATA_IP}"
+      # - name: Debug XLA (run container)
+      #   run: |
+
+      #     METADATA_IP=$(getent hosts metadata.google.internal | awk '{ print $1 }')
+      #     echo "Found metadata server IP: ${METADATA_IP}"
           
-          if [ -z "${METADATA_IP}" ]; then
-            echo "Error: Could not resolve metadata.google.internal"
-            exit 1
-          fi
+      #     if [ -z "${METADATA_IP}" ]; then
+      #       echo "Error: Could not resolve metadata.google.internal"
+      #       exit 1
+      #     fi
 
-          docker run --rm \
-            --shm-size=16G \
-            --privileged \
-            --network host \
-            --ipc host \
-            --add-host "metadata.google.internal:${METADATA_IP}" \
-            debug-dind
+      #     docker run --rm \
+      #       --shm-size=16G \
+      #       --privileged \
+      #       --network host \
+      #       --ipc host \
+      #       --add-host "metadata.google.internal:${METADATA_IP}" \
+      #       debug-dind
 
 
 #     docker run -d --name tgi-tests-${MODEL_ID##*/} \
